language: node_js
node_js:
- "14.16.0"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run tests/collection postman.json -d C:\Users\Utilisateur\Desktop\Postman-project\postmanProject\jsonFile